services:
  # Mongodb service
  mongo_db:
    container_name: dealerships_services_container
    image: mongo:latest
    ports:
      - 27018:27017
    restart: always
    volumes:
      - mongo_data:/data/db

 # Database Node api service
  database_api:
    build:
        context: ./database
        dockerfile: Dockerfile
    image: nodeapp_database
    ports:
      - 3030:3030
    depends_on: 
      - mongo_db

  # Cars Inventory Node api service
  cars_inventory_api:
    build:
        context: ./carsInventory
        dockerfile: Dockerfile
    image: nodeapp_carsinventory
    ports:
      - 3050:3050
    depends_on: 
      - mongo_db
      - database_api
    restart: always

volumes:
  mongo_data: {}